packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@tanstack/react-query': 5.90.12
  '@tanstack/react-query-devtools': 5.91.1
  '@types/node': 24.9.2
  '@types/react': 19.2.0
  '@types/react-dom': 19.2.0
  '@vitest/coverage-istanbul': '4.0.16'
  'happy-dom': '20.0.11'
  'react': '19.2.0'
  'react-dom': '19.2.0'
  'react-router': '^7.9.5'
  'zod': '^3.25.76'
  'vitest': '4.0.16'
  'vite': '^7.1.12'
  'typescript': '^5.9.3'
  'msw': '^2.12.4'
  'uuid': '^11.0.3'
  'date-fns': '^4.1.0'

