packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@types/node': 24.9.2
  '@types/react': 19.2.0
  '@vitest/coverage-istanbul': '^4.0.7'
  'react': '19.2.0'
  'react-dom': '19.2.0'
  'react-router': '^7.9.5'
  'zod': '^3.25.76'
  'vitest': '^4.0.7'
  'vite': '^7.1.12'
  'typescript': '^5.9.3'

