// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/state-machine/:id?': {
    params: {
      id?: string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/state-machine/:id?';
  };
  'routes/index.tsx': {
    id: 'routes/index';
    page: '/';
  };
  'routes/state-machine.tsx': {
    id: 'routes/state-machine';
    page: '/state-machine/:id?';
  };
};

type RouteModules = {
  root: typeof import('./app/root.tsx');
  'routes/index': typeof import('./app/routes/index.tsx');
  'routes/state-machine': typeof import('./app/routes/state-machine.tsx');
};
